name: Python linting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Python Checkstyle
        timeout-minutes: 20
        run: |
          pylint --rcfile=./.pylintrc ./server/*/*.py
        with:
          files: server/

