name: Server unit tests
on: [push]
jobs:
  server-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Python Unit Tests
      timeout-minutes: 20
      run: |
        set -x
        for SERVICE in "contacts" "userservice"; do
          echo "testing $SERVICE..."
          pushd src/$SERVICE
            python3 -m venv $HOME/venv-$SERVICE
            source $HOME/venv-$SERVICE/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python -m pytest -v -p no:warnings
            deactivate
          popd
        done
      with:
        files: server/
